

game:main.o obstacle.o
	gcc main.o obstacle.o -o game  -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g 

main.o:main.c
	gcc main.c -c  -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g


obstacle.o:obstacle.c
	gcc obstacle.c -c -lSDL -lSDL_image -lSDL_mixer -lSDL_ttf -g
